@include('main.layout.header')
<body>
@include('main.layout.rightBanner')
{{--@include('main.layout.navbar')--}}
@include('main.layout.navbar')
@include('main.layout.image')
<div>
    @yield('heroes')
    @yield('gallery')
    @yield('heroDetails')
</div>
</body>
@include('main.layout.footer')
